server:  
  port: ${PORT:9999}

spring:  
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: vpn
    password: vpn
    
logging:
  level:
    org.springframework.security: TRACE
      
security:
#  basic:
#    enabled: false
  user:
    name: root
    password: password
  oauth2:
    client:
      client-id: acme
      client-secret: secret
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/